default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  timeout: 500
development:
  <<: *default
  database: billinho_db
test:
  <<: *default
  database: billinho_db
production:
  <<: *default
  database: billinho_db




