name: (Billinho) CI RSpec Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec spec
